# fly.toml app configuration file generated for m3o on 2025-07-30T09:27:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'm3o'
primary_region = 'gru'

[build]
  build-target = "production"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
