name: Create Release on version change

on:
  push:
    paths:
      - deno.json
      - .github/workflow/publish.yml

jobs:
  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4

      - name: Create release from tag
        uses: marco-souza/tag-release@1.2.0
        uses: ./
        with:
          title: 🚀 Release
          version-file: deno.json
          token: ${{ secrets.GITHUB_TOKEN }}
